### ISSUE TITLE
KeyError when visualizing tournament

### ISSUE THREAD

**Issue by jacksondc** [yasserfarouk/scml-vis#1]
I'm getting errors when I try to visualize the logs from a tournament run:

```
> scml-vis show -f ~/negmas/tournaments/20210507H154058452055vSP-stage-0001                 
Processing 20210507H154058452055vSP-stage-0001 [0 of 1]
        World 0000PT_R-Go29R.00 [0 of 4]
Traceback (most recent call last):
  File "/Users/jacksondc/Development/scml/.venv3.9/bin/scml-vis", line 8, in <module>
    sys.exit(main())
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/scml_vis/cli.py", line 50, in show
    compiler.main(folder, max_worlds)
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/scml_vis/compiler.py", line 765, in main
    ) = get_data(folder)
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/scml_vis/compiler.py", line 673, in get_data
    ag, pr, wo, co, cs, ng, of, ns, br = parse_world(
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/scml_vis/compiler.py", line 316, in parse_world
    negotiations["buyer_type"] = negotiations.buyer.apply(do_map)
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/pandas/core/series.py", line 4138, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2467, in pandas._libs.lib.map_infer
  File "/Users/jacksondc/Development/scml/.venv3.9/lib/python3.9/site-packages/scml_vis/compiler.py", line 314, in do_map
    return atmap[x]
KeyError: '06Ran@1'
```

Expected behavior: I think should be launching the visualizer.

I ran the tournament with

```py
anac2021_oneshot(competitors=[RandomOneShotAgent, GreedyOneShotAgent], verbose=True, n_steps=10, n_configs=2)
```

- `scml-vis` version: 0.2.2
- Python version: 3.9
- OS: Mac

**Comment by yasserfarouk** [comment]
what are the scml and negmas versions?
You can get them by running:

>> scml --version

**Comment by yasserfarouk** [comment]
I could reproduce the issue. Will return to you once it is resolved. Thanks

**Comment by jacksondc** [comment]
Thank you!

Just in case, scml version is 0.4.1, negmas is 0.8.1.

**Comment by yasserfarouk** [comment]
Just pushed a quick bugfix. Please check it by installing the latest version on github. I will reopen the issue until you confirm.

**Comment by jacksondc** [comment]
Working for me now!
